[package]
name = "circuit"
version = "0.0.0"
edition = "2024"

[[bin]]
name = "circuit"
path = "src/main.rs"

[dependencies]
x25519-dalek = { version = "2", features = ["static_secrets"] }
chacha20poly1305 = "0.10"
chacha20 = "0.9"
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand = "0.8"
sha2 = "0.10"
hkdf = "0.12"
